name: CI

on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 11.6.0
        uses: actions/setup-node@v1
        with:
          node-version: 11.6.0
      - name: Install dependencies
        run: |
          npm install -g elm
      - name: Build project
        env:
          CI: true
        run: |
          elm make src/Main.elm

  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 11.6.0
        uses: actions/setup-node@v1
        with:
          node-version: 11.6.0
      - name: Install dependencies
        run: |
          npm install -g elm elm-test elm-verify-examples
      - name: Run tests
        env:
          CI: true
        run: |
          elm-verify-examples
          elm-test

  Analyse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 11.6.0
        uses: actions/setup-node@v1
        with:
          node-version: 11.6.0
      - name: Install dependencies
        run: |
          npm install -g elm-analyse
      - name: Analyse program
        env:
          CI: true
        run: |
          elm-analyse
