name: Build and Test CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 11.6.0
        uses: actions/setup-node@v1
        with:
          node-version: 11.6.0
      - name: Build project
        env:
          CI: true
        run: |
          npm install -g elm
          elm make src/Main.elm
      - name: Run tests
        env:
          CI: true
        run: |
          npm install -g elm-test elm-verify-examples
          elm-verify-examples
          elm-test
